site_name: objio
nav:
    - Home: index.md
    - Examples: examples.md
    - Configuration: configuration.md
    - Development: development.md
    - Pydoc: pydoc.md
    - Command Line Usage: commands.md
theme: readthedocs
