site_name: objectio
nav:
    - Home: index.md
    - Examples: examples.md
    - Configuration: configuration.md
    - Development: development.md
    - Module Docs: pydoc.md
    - Command Usage: commands.md
theme: readthedocs
