name: publish on pypi
on: [push]
jobs:
  publish:
    name: build-and-publish
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install
      run: >-
        pip3 install -U -r requirements.dev.txt
        pip3 install -U -r requirements.txt
        pytest
        python3 setup.py sdist bdist_wheel
    - name: publish to test.pypi.org
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: publish to pypi.org
      if: startsWith(github.even.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
